# -*- coding: utf-8 -*-
"""future path.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wIhaBWLcfAQK-xIvg5HDw1v4GwPCzf24
"""

# -*- coding: utf-8 -*-
from collections import OrderedDict
import streamlit as st

# ------------------ HIDE DEFAULT STREAMLIT MENU ------------------
st.markdown("""
    <style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}
    </style>
    """, unsafe_allow_html=True)

st.set_page_config(page_title="منصه تخصصي", layout="centered")

# ------------------ GLOBAL STYLE ------------------
st.markdown("""
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Tajawal:wght@400;500;700&display=swap');

        body {
            direction: rtl;
            text-align: right;
            background-color: #F9F7F1;
        }

        * {
            font-family: 'Tajawal', sans-serif !important;
        }

        h1, h2 {
            text-align: center !important;
            font-weight: 700;
            color: #2C2C2C;
            text-shadow: 0px 1px 4px rgba(0, 0, 0, 0.1);
        }

        label, .stNumberInput label {
            font-size: 16px;
            font-weight: 500;
            color: #444;
        }

        .stTextInput > div > div > input,
        .stNumberInput > div > div > input {
            text-align: right;
            font-size: 15px;
        }

        .stNumberInput {
            margin-bottom: 20px;
        }
    </style>
""", unsafe_allow_html=True)


# ------------------ UNIVERSITY SELECTION ------------------
st.markdown("<h1 style='text-align: right;'>اختر الجامعة</h1>", unsafe_allow_html=True)

university = st.selectbox(
    "اختر الجامعة:",
    [
        "جامعة الكويت",
        "الجامعة الأمريكية في الشرق الأوسط (AUM)",
        "الجامعة الأمريكية في الكويت (AUK)",
        "الجامعة الخليجية للعلوم والتكنولوجيا (GUST)"
    ]
)

st.markdown(f"<h1 style='text-align:right;'>ابحث عن التخصص المناسب لك في {university}</h1>", unsafe_allow_html=True)

# ------------------ INPUT FIELDS ------------------
if university == "جامعة الكويت":
    st.subheader("أدخل درجاتك")
    gpa = st.number_input(" معدل الثانوية العامة ٪", 0.0, 100.0, step=0.01, format="%g")
    math = st.number_input(" درجة القدرات – رياضيات ٪", 0.0, 100.0, step=0.01, format="%g")
    english = st.number_input(" درجة القدرات – إنجليزي ٪", 0.0, 100.0, step=0.01, format="%g")
    arabic = st.number_input(" درجة القدرات – عربي ٪ (إذا كانت مطلوبة)", 0.0, 100.0, step=0.01, format="%g")
    french = st.number_input(" درجة القدرات – فرنسي ٪ (إذا كانت مطلوبة)", 0.0, 100.0, step=0.01, format="%g")

elif university == "الجامعة الأمريكية في الشرق الأوسط (AUM)":
    st.subheader("أدخل بياناتك")
    gpa = st.number_input(" معدل الثانوية العامة ٪", 0.0, 100.0, step=0.01, format="%g")
    english = st.number_input(" درجة اختبار اللغة الإنجليزية (IELTS أو TOEFL) ٪", 0.0, 100.0, step=0.01, format="%g")
    math, arabic, french = 0, 0, 0

elif university == "الجامعة الأمريكية في الكويت (AUK)":
    st.subheader("أدخل بياناتك")
    gpa = st.number_input(" معدل الثانوية العامة ٪", 0.0, 100.0, step=0.01, format="%g")
    english = st.number_input(" درجة اللغة الإنجليزية ٪", 0.0, 100.0, step=0.01, format="%g")
    math, arabic, french = 0, 0, 0

elif university == "الجامعة الخليجية للعلوم والتكنولوجيا (GUST)":
    st.subheader("أدخل بياناتك")
    gpa = st.number_input(" معدل الثانوية العامة ٪", 0.0, 100.0, step=0.01, format="%g")
    english = st.number_input(" درجة اختبار اللغة الإنجليزية ٪", 0.0, 100.0, step=0.01, format="%g")
    math, arabic, french = 0, 0, 0


# ------------------ INTEREST SELECTION ------------------
st.subheader("اختيار مجال اهتمامك")
interest = st.selectbox(" شنو نوع التخصصات اللي تميل لها أكثر؟", [
    "المجال الطبي والصحي 🏥",
    "الهندسة والتقنية ⚙️",
    "التحليل والرياضيات 📊",
    "القانون والقراءة 📚",
    "الفنون والتصميم 🎨",
    "العلوم الطبيعية 🧪",
    "التربية والتعليم 👩‍🏫"
])

# ------------------ STREAM SELECTION (FOR KU ONLY) ------------------
if university == "جامعة الكويت":
    stream = st.radio("هل أنت من المسار العلمي أم الأدبي؟", ["علمي", "أدبي"])
else:
    stream = "علمي"

# ------------------ UNIVERSITIES AND COLLEGES DATA ------------------

# --- جامعة الكويت ---
kuwait_university_colleges = OrderedDict({
    # Paste your full KU data dictionary here exactly as before
})

# --- الجامعة الأمريكية في الشرق الأوسط (AUM) ---
aum_colleges = {
    "College of Engineering and Technology": {
        "weights": {"gpa": 80, "english": 20},
        "min_score": 70.0,
        "interests": ["الهندسة والتقنية ⚙️", "التحليل والرياضيات 📊"],
        "years": 4,
        "paths": ["Mechanical Engineering", "Civil Engineering", "Computer Engineering", "Industrial Engineering"]
    },
    "College of Business Administration": {
        "weights": {"gpa": 85, "english": 15},
        "min_score": 65.0,
        "interests": ["التحليل والرياضيات 📊", "القانون والقراءة 📚"],
        "years": 4,
        "paths": ["Finance", "Marketing", "Accounting", "Management Information Systems"]
    },
    "College of Design": {
        "weights": {"gpa": 80, "english": 20},
        "min_score": 65.0,
        "interests": ["الفنون والتصميم 🎨"],
        "years": 4,
        "paths": ["Graphic Design", "Interior Design"]
    }
}

# --- الجامعة الأمريكية في الكويت (AUK) ---
auk_colleges = {
    "College of Arts and Sciences": {
        "weights": {"gpa": 85, "english": 15},
        "min_score": 60.0,
        "interests": ["القانون والقراءة 📚", "الفنون والتصميم 🎨"],
        "years": 4,
        "paths": ["English Literature", "Communication & Media", "Graphic Design", "International Relations"]
    },
    "College of Business and Economics": {
        "weights": {"gpa": 85, "english": 15},
        "min_score": 60.0,
        "interests": ["التحليل والرياضيات 📊"],
        "years": 4,
        "paths": ["Accounting", "Finance", "Marketing", "Management"]
    },
    "College of Engineering and Applied Sciences": {
        "weights": {"gpa": 80, "english": 20},
        "min_score": 70.0,
        "interests": ["الهندسة والتقنية ⚙️"],
        "years": 4,
        "paths": ["Computer Engineering", "Electrical Engineering"]
    }
}

# --- الجامعة الخليجية للعلوم والتكنولوجيا (GUST) ---
gust_colleges = {
    "College of Business Administration": {
        "weights": {"gpa": 85, "english": 15},
        "min_score": 70.0,
        "interests": ["التحليل والرياضيات 📊"],
        "years": 4,
        "paths": ["Accounting", "Finance", "Marketing", "Management", "Economics"]
    },
    "College of Arts and Humanities": {
        "weights": {"gpa": 90, "english": 10},
        "min_score": 65.0,
        "interests": ["القانون والقراءة 📚", "الفنون والتصميم 🎨"],
        "years": 4,
        "paths": ["English Literature", "Mass Communication", "Public Relations", "Linguistics"]
    }
}

universities = {
    "جامعة الكويت": kuwait_university_colleges,
    "الجامعة الأمريكية في الشرق الأوسط (AUM)": aum_colleges,
    "الجامعة الأمريكية في الكويت (AUK)": auk_colleges,
    "الجامعة الخليجية للعلوم والتكنولوجيا (GUST)": gust_colleges
}


# ------------------ RESULTS SECTION ------------------
if st.button(" اقترح التخصصات"):
    matched = []
    selected_colleges = universities[university]

    for name, data in selected_colleges.items():
        if "stream" in data and data["stream"] != stream:
            continue

        if interest not in data["interests"]:
            continue

        weights = data["weights"]
        score = 0
        if "gpa" in weights:
            score += gpa * (weights["gpa"] / 100)
        if "math" in weights:
            score += math * (weights["math"] / 100)
        if "english" in weights:
            score += english * (weights["english"] / 100)
        if "arabic" in weights:
            score += arabic * (weights["arabic"] / 100)
        if "french" in weights:
            score += french * (weights["french"] / 100)

        final_score = round(score, 2)

        if final_score >= data["min_score"]:
            matched.append((name, data, final_score))

    if matched:
        st.success(" هذه التخصصات تناسبك حسب درجاتك واهتماماتك")
        for name, data, final_score in matched:
            paths = ", ".join(data["paths"]) if "paths" in data else "غير محدد"
            st.markdown(f"""
            <div style='border-right: 6px solid #003366; padding: 20px 25px; margin: 20px 0; background-color: #f9f9f9; border-radius: 10px;'>
                <h3 style='margin-bottom: 10px;'>{name}</h3>
                <p><strong> معدلك المكافئ:</strong> {final_score}%</p>
                <p><strong> سنوات الدراسة:</strong> {data['years']} سنوات</p>
                <p><strong> البرامج المتاحة:</strong> {paths}</p>
            </div>
            """, unsafe_allow_html=True)

        st.markdown("""
        <div style='text-align:center; font-size:13px; color:#666; margin-top:30px;'>
            📌 <em>المعلومات مبنية على بيانات رسمية من الجامعات للسنة الدراسية 2025–2026. قد تتغير المعدلات في السنوات القادمة.</em>
        </div>
        """, unsafe_allow_html=True)
    else:
        st.warning("عذرًا، لم نجد تخصصات تتوافق مع درجاتك واهتماماتك. جرّب مجال آخر أو تحقق من بياناتك.")